// src/components/QrApproved.tsx  —  Figma frame: resident-qr-approved
import { useState } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import * as Clipboard from 'expo-clipboard';
import { Copy, Check } from 'lucide-react-native';
import { Household } from '../data/household';
import { colors, fonts } from '../constants/theme';

const GUIDELINES = [
  'Present this digital QR to LGU personnel during relief operation dispatch.',
  'Keep the reference number private. Do not share screenshots of this QR on social media.',
];

export default function QrApproved({ household }: { household: Household }) {
  const [copied, setCopied] = useState(false);
  const referenceNumber = household.referenceNumber ?? '';
  const qrToken = household.qrToken ?? '';

  const copyReference = async () => {
    await Clipboard.setStringAsync(referenceNumber);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <View style={styles.container}>
      <View style={styles.card}>
        {/* header */}
        <View style={styles.pill}>
          <Text style={styles.pillText}>Active Beneficiary</Text>
        </View>
        <Text style={styles.name}>{household.householdName}</Text>
        <Text style={styles.address}>Barangay {household.barangay}</Text>

        {/* QR code — content issued by the admin, not generated by the app */}
        <View style={styles.qrWrapper}>
          <QRCode value={qrToken} size={148} color={colors.text} backgroundColor={colors.white} />
        </View>

        {/* reference number */}
        <View style={styles.refField}>
          <Text style={styles.refLabel}>Household Reference Number</Text>
          <View style={styles.refInput}>
            <Text style={styles.refValue}>{referenceNumber}</Text>
            <Pressable style={styles.copyBtn} onPress={copyReference} hitSlop={8}>
              {copied ? (
                <Check size={14} color={colors.primary} strokeWidth={2} />
              ) : (
                <Copy size={14} color={colors.primary} strokeWidth={2} />
              )}
            </Pressable>
          </View>
        </View>
      </View>

      {/* usage guidelines */}
      <View style={styles.guidelines}>
        <Text style={styles.guidelinesTitle}>How to use this QR Code</Text>
        {GUIDELINES.map((text) => (
          <View key={text} style={styles.bulletRow}>
            <Text style={styles.bullet}>•</Text>
            <Text style={styles.bulletText}>{text}</Text>
          </View>
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { gap: 20 },

  card: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  pill: { backgroundColor: colors.primaryTint, borderRadius: 4, paddingHorizontal: 8, height: 20, justifyContent: 'center' },
  pillText: { fontFamily: fonts.bold, fontSize: 10, color: colors.primary },
  name: { fontFamily: fonts.extrabold, fontSize: 20, color: colors.text, textAlign: 'center', marginTop: 4 },
  address: { fontFamily: fonts.regular, fontSize: 12, color: colors.textSecondary, textAlign: 'center', marginTop: 4 },

  qrWrapper: {
    marginTop: 20,
    width: 180,
    height: 180,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  refField: { alignSelf: 'stretch', marginTop: 20, gap: 6 },
  refLabel: { fontFamily: fonts.semibold, fontSize: 11, color: colors.muted },
  refInput: {
    height: 44,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingLeft: 16,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refValue: { fontFamily: fonts.bold, fontSize: 14, color: colors.text },
  copyBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },

  guidelines: { backgroundColor: colors.primaryTint, borderRadius: 12, padding: 16, gap: 12 },
  guidelinesTitle: { fontFamily: fonts.bold, fontSize: 12, color: colors.primary },
  bulletRow: { flexDirection: 'row', gap: 8 },
  bullet: { fontFamily: fonts.regular, fontSize: 11, color: colors.primary },
  bulletText: { flex: 1, fontFamily: fonts.regular, fontSize: 11, lineHeight: 15, color: colors.textSecondary },
});