<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1f2933; }
        .header { border-bottom: 2px solid #2e7d67; padding-bottom: 8px; margin-bottom: 12px; }
        h1 { font-size: 16px; margin: 0; color: #2e7d67; }
        .meta { color: #52606d; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #2e7d67; color: #fff; text-align: left; padding: 5px; }
        td { padding: 4px 5px; border-bottom: 1px solid #e4e7eb; }
        tr:nth-child(even) td { background: #f5f7fa; }
        .empty { text-align: center; padding: 20px; color: #7b8794; }
        .footer { margin-top: 16px; font-size: 9px; color: #7b8794; }
        .summary { width: 100%; margin-bottom: 12px; border-collapse: separate; border-spacing: 6px 0; }
        .summary td { border: 1px solid #d9e2ec; background: #f5f7fa; padding: 6px 8px; width: 25%; }
        .summary .label { font-size: 8px; text-transform: uppercase; color: #52606d; }
        .summary .value { font-size: 13px; font-weight: bold; color: #1f2933; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ReliefConnect: {{ $title }}</h1>
        <div class="meta">
            Municipality of Urbiztondo, Pangasinan &middot;
            Period: {{ $from->format('M d, Y') }} to {{ $to->format('M d, Y') }} &middot;
            Generated by {{ $generatedBy }} on {{ now()->format('M d, Y h:i A') }}
        </div>
    </div>

    @if (!empty($summary))
        <table class="summary">
            <tr>
                @foreach ($summary as $label => $value)
                    <td><div class="label">{{ $label }}</div><div class="value">{{ $value }}</div></td>
                @endforeach
            </tr>
        </table>
    @endif

    <table>
        <thead>
            <tr>@foreach ($headers as $h)<th>{{ $h }}</th>@endforeach</tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>@foreach ($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>
            @empty
                <tr><td class="empty" colspan="{{ count($headers) }}">No records in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Total records: {{ count($rows) }}. This report contains personal information protected under RA 10173 (Data Privacy Act of 2012).
    </div>
</body>
</html>
