/**
 * Builds a real .xlsx file in the browser from a report preview
 * ({ title, summary, headers, rows, period, generated_by, filename }).
 * exceljs is loaded only when someone exports, so it doesn't slow down the app.
 */
export async function exportExcel(report) {
  const { default: ExcelJS } = await import('exceljs')
  const wb = new ExcelJS.Workbook()
  wb.creator = 'ReliefConnect'
  const ws = wb.addWorksheet(report.title.slice(0, 31))
  const cols = report.headers.length

  ws.addRow([`ReliefConnect: ${report.title}`])
  ws.mergeCells(1, 1, 1, cols)
  ws.getRow(1).font = { bold: true, size: 14, color: { argb: 'FF2E7D67' } }
  ws.addRow([`Municipality of Urbiztondo, Pangasinan · Period: ${report.period.from} to ${report.period.to} · Generated by ${report.generated_by}`])
  ws.mergeCells(2, 1, 2, cols)
  ws.getRow(2).font = { size: 9, color: { argb: 'FF52606D' } }
  ws.addRow([])

  Object.entries(report.summary ?? {}).forEach(([label, value]) => {
    const r = ws.addRow([label, value])
    r.getCell(1).font = { bold: true, color: { argb: 'FF52606D' } }
  })
  ws.addRow([])

  const header = ws.addRow(report.headers)
  header.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2E7D67' } }
  })
  const headerRow = header.number
  report.rows.forEach((row) => ws.addRow(row))
  ws.views = [{ state: 'frozen', ySplit: headerRow }]
  ws.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: cols } }

  // Column widths from the longest value in each column
  report.headers.forEach((h, i) => {
    const longest = Math.max(String(h).length, ...report.rows.map((r) => String(r[i] ?? '').length))
    ws.getColumn(i + 1).width = Math.min(Math.max(longest + 2, 10), 48)
  })

  ws.addRow([])
  ws.addRow(['This report contains personal information protected under RA 10173 (Data Privacy Act of 2012).'])
    .font = { italic: true, size: 8, color: { argb: 'FF7B8794' } }

  const blob = new Blob([await wb.xlsx.writeBuffer()], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${report.filename}.xlsx`
  a.click()
  URL.revokeObjectURL(a.href)
}
